my_dbt_project:
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
      connect_timeout: 10
  target: dev
